spin_manifest_version = 2

[application]
name = "challenge"
version = "0.1.0"
authors = ["DanStough <Daniel.Stough@gmail.com>"]
description = "advent of spin challenge 1"

[[trigger.http]]
route = "/data"
component = "challenge"

[component.challenge]
source = "target/wasm32-wasi/release/challenge.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.challenge.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "static-server"

[component.static-server]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "static", destination = "/" }]
